// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCM-KaVG-ZfwJxoprdZX-dHJCLHUJF9C_k",
    authDomain: "fenjoy-1b5d7.firebaseapp.com",
    projectId: "fenjoy-1b5d7",
    storageBucket: "fenjoy-1b5d7.appspot.com",
    messagingSenderId: "222050806709",
    appId: "1:222050806709:web:feed117c1d320accf3c7fc",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDekbJwrmUK0rIl1sXRNqh3sfmRWZKnzzU',
    appId: '1:222050806709:android:5bdf147844d66d72f3c7fc',
    messagingSenderId: '222050806709',
    projectId: 'fenjoy-1b5d7',
    storageBucket: 'fenjoy-1b5d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcj5LwMbJzU6tAXFUVcMf7Igeb1uIfPHw',
    appId: '1:222050806709:ios:a24f75e5acbcb385f3c7fc',
    messagingSenderId: '222050806709',
    projectId: 'fenjoy-1b5d7',
    storageBucket: 'fenjoy-1b5d7.appspot.com',
    // iosClientId: '174457943368-7fq2ra4qbtcs4dqhq845ub6o30eede4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.fenjoy',
  );
}
